# Generated by Django 4.0.1 on 2022-01-11 20:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_img',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://image.shutterstock.com/image-vector/modern-id-card-photo-man-260nw-1718677939.jpg', max_length=255, verbose_name='image'),
        ),
    ]
