# Generated by Django 4.0.1 on 2022-02-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0004_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FuelReplenish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.IntegerField()),
                ('replenished_amount', models.IntegerField()),
                ('batch_no', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment', to='defco.station')),
            ],
        ),
    ]
