# Generated by Django 4.0.1 on 2022-02-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0006_station_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelreplenish',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
    ]
