# Generated by Django 4.0.1 on 2022-02-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0007_alter_fuelreplenish_current_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelreplenish',
            options={'ordering': ['-pk']},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=255)),
                ('attendant', models.IntegerField()),
                ('date', models.DateField()),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='defco.fuelreplenish')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='defco.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='defco.vehicle')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
