# Generated by Django 4.0.1 on 2022-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_attendant',
            field=models.BooleanField(default=False),
        ),
    ]
