# Generated by Django 4.0.1 on 2022-03-01 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0010_user_is_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
