# Generated by Django 4.0.1 on 2022-03-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0011_alter_transaction_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
