# Generated by Django 4.0.1 on 2022-03-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reveal_id',
            field=models.BooleanField(default=False),
        ),
    ]
