# Generated by Django 4.0.1 on 2022-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0014_review_reveal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
