# Generated by Django 4.0.1 on 2022-03-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0015_alter_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
