# Generated by Django 4.0.1 on 2022-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0018_qrcode_alter_reply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
    ]
