# Generated by Django 4.0.1 on 2022-03-31 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0019_alter_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='vehicle',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='defco.vehicle'),
        ),
    ]
