# Generated by Django 4.0.1 on 2022-04-11 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0020_qrcode_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='defco.vehicle')),
            ],
        ),
    ]
