# Generated by Django 4.0.1 on 2022-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0021_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
