# Generated by Django 4.0.1 on 2022-05-11 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0026_alter_flag_options_dailylitrerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreplenish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
