# Generated by Django 4.0.1 on 2022-05-13 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0028_station_created_at_vehicle_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='vehicleapproval', to='defco.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='UserApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='userapproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
