# Generated by Django 4.0.1 on 2022-05-16 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0030_userlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='defco.station')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
