# Generated by Django 4.0.1 on 2022-05-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defco', '0031_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QrCd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.CharField(max_length=1000)),
                ('vehicle', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='qrcd', to='defco.vehicle')),
            ],
        ),
    ]
